# Copyright 2019-2026 SURF, GÉANT.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The workflow form-fill skill: a deterministic walk over core's form, answered by a human in the loop.

A form is filled through a human-in-the-loop transport only (kagent's extension over A2A, or LibreChat's
ask-user tool over chat completions): every stop of the skill is a pause that shows the human the page's
questions with their options, or the start to approve, and only their structured response continues the form. No chat text is read for a value or a
decision, by this code or by a model. *Which* workflow a request asks for is the model's call: it hands
off with the ``start_workflow_form`` tool (``handoff``, which checks the key against core's catalogue)
and ``open`` walks the first pages in the same turn. Core's own validation is the only validation. One
skill turn is one response of the human:

- opening (just handed off): the form is **walked** from page 0 with the subscription the model passed
  on; a subscription core will not run the workflow on is rejected by core's own subscription page, like
  any other value.
- gathering: the answers are recorded, then the form is walked again from page 0, each page submitted
  to core as it is known; the walk stops at the first page core does not accept — its fields are the
  questions, with core's message on the ones it rejected — or at the summary. Where core rejects what a
  person typed for a field, an ``Interpreter`` turns the words into the field's value once, then core
  decides again.
- confirming: the start is the human's approval of the ``create_workflow`` call (exactly the last walk's
  validated pages); a rejection cancels. A start is sent once: only core's own verdict on the pages
  reopens the form, any other failure closes it.

A message that carries no response means the pending stop went unanswered: the form is over and the
message is the model's. The one exception is a stop that has not been shown yet (``unseen``): a parent
runtime pauses once per call, so the stop that answers a response only reaches the human when the
parent calls again, and that call shows it.

Core describes each page as data (``get_workflow_form`` with ``include_schema=false``: its ``fields``, and
with ``verdict="result"`` a rejected page as a result with its ``errors``), and everything here reads that
data as it is. Re-walking from page 0 every turn is what makes corrections free (pages after a changed
answer are regenerated by core) and keeps the session tiny; each page costs one MCP call. Routing by a
typed decision engine in front of the model, and prefilling pages from the conversation, live on the Jev
branch.
"""

from __future__ import annotations

import hashlib
import json
import time
from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from dataclasses import field as dc_field
from typing import Any, Literal, Protocol

import structlog
from orchestrator.core.schemas.mcp_tools import FormField, FormFieldError, GetWorkflowFormRequest, WorkflowFormPage
from orchestrator.core.schemas.process import ProcessIdSchema
from orchestrator.core.schemas.workflow import WorkflowSchema
from pydantic import TypeAdapter, ValidationError
from pydantic_ai import ModelRetry

from orchestrator_agent.form_fill.interpret import Interpreter
from orchestrator_agent.form_fill.model import askable, form_model, label_of, options_of
from orchestrator_agent.state import (
    SUBSCRIPTION_ID,
    Approval,
    AskField,
    Decision,
    FormFillSession,
    FormInput,
    FormReply,
    Reply,
    SearchState,
)
from orchestrator_agent.tool_names import (
    CREATE_WORKFLOW_TOOL,
    GET_WORKFLOW_FORM_TOOL,
    JSON_DATA_PARAM,
    LIST_WORKFLOWS_TOOL,
    WORKFLOW_KEY_PARAM,
)

logger = structlog.get_logger(__name__)

# Core's tool results are validated with core's own response models (the agent depends on orchestrator-core),
# and its tool arguments are built from core's request models — nothing here spells out a field of either.
_WORKFLOW_LIST: TypeAdapter[list[WorkflowSchema]] = TypeAdapter(list[WorkflowSchema])


class CallTool(Protocol):
    """Call one of core's MCP tools by name (bound to an open MCP session by the adapter)."""

    async def __call__(self, name: str, args: dict[str, Any]) -> Any: ...


_MAX_PAGES = 50  # a form that keeps producing pages is broken, not long
_WORKFLOWS_TTL = 300.0  # seconds the workflow catalogue is cached per skill instance

# Core's ``format`` markers the skill acts on (pydantic-forms' field types).
ACCEPT = "accept"  # consent, given once per page by picking its one option
SUMMARY = "summary"  # a table of the workflow's own recap: shown, never filled
_MISSING = "missing"  # pydantic's error type for a required field without a value: the question says so already


def as_reply(data: FormReply, *, ask: Sequence[AskField] | None = None, approval: Approval | None = None) -> Reply:
    return Reply(data.as_text(), ask=ask, approval=approval)


def questions(
    fields: Sequence[FormField], values: Mapping[str, Any], errors: Sequence[FormFieldError], reason: str | None = None
) -> list[AskField]:
    """The stop as questions for the human: the fields core rejected, with its message, then the unanswered ones.

    A page core refused without naming one of its fields — its errors name none, or the refusal is no form
    verdict at all (``reason``) — is asked again in full, the first question with what core said.
    """
    asked = {field.name: field for field in fields if askable(field)}
    problems: dict[str, str] = {}
    for error in errors:
        if error.loc and (name := str(error.loc[0])) in asked:
            problems.setdefault(name, "" if error.type == _MISSING else error.msg)
    if (errors or reason) and not problems:
        said = "; ".join(error.msg for error in errors) or str(reason)
        problems = {name: said if index == 0 else "" for index, name in enumerate(asked)}
    stop = [question(asked[name], problem) for name, problem in problems.items()]
    return stop + [question(field) for name, field in asked.items() if name not in problems and name not in values]


def question(field: FormField, problem: str = "") -> AskField:
    """One field as a question: its title, whether it is required, its options as chips, core's message if it rejected the answer.

    Nothing spells out what the field expects: a person answers in words, the interpreter has the schema.
    """
    note = "required" if field.required else "optional — leave empty to keep the default"
    text = f"{field.title} (`{field.name}`, {note})" + (f" — {problem}" if problem else "")
    options = options_of(field)
    values: tuple[Any, ...] = tuple(option.value for option in options) if options is not None else ()
    if options is None and field.kind == "boolean":
        values = (True, False)
    shown = {str(option.value): option.label for option in options or []}
    return AskField(
        name=field.name,
        question=text,
        choices=unique_choices(values, shown),  # the human sees labels, told apart where they coincide
        values=values,
        multiple=field.kind == "list",
        required=field.required,
        title=field.title,
        problem=problem,
    )


def unique_choices(options: Sequence[Any], shown: Mapping[str, str]) -> tuple[str, ...]:
    """The options as a person sees them: each by its label, with its value added where labels coincide.

    Labels are descriptions and descriptions are not unique, while a chip's text is all a transport gets
    back from a pick; two options must never read the same, or a pick could not be mapped to the value core
    takes (an id, never a label). The value is what tells them apart, and it is what the person confirms.
    """
    texts = [shown.get(str(value), str(value)) for value in options]
    counts = Counter(texts)
    return tuple(f"{text} ({value})" if counts[text] > 1 else text for text, value in zip(texts, options, strict=True))


def single_pick(field: FormField) -> bool:
    """A field that takes one of its options: a choice, or a list of at most one (a single-select ``choice_list``)."""
    return options_of(field) is not None and (field.kind != "list" or field.constraints.get("max_length") == 1)


def _fields(session: FormFillSession) -> dict[str, FormField]:
    """The fields of the walked pages by name (a later page wins a name)."""
    return {field.name: field for page in session.pages for field in page.fields or []}


def _given(session: FormFillSession) -> dict[str, Any]:
    """The validated pages' values as one mapping: what would be submitted (a later page wins a name)."""
    return {name: value for page in session.page_inputs for name, value in page.items()}


def _fingerprint(pages: list[dict[str, Any]]) -> str:
    """What a consent is given for — the pages before it and the rest of its own — as one comparable string."""
    return hashlib.sha256(json.dumps(pages, sort_keys=True, default=str).encode()).hexdigest()


@dataclass
class FormFillSkill:
    interpret: Interpreter | None = None  # a person's answers core rejected -> the values the fields expect
    _catalogue: dict[str, str] | None = dc_field(default=None, init=False, repr=False)
    _catalogue_at: float = dc_field(default=0.0, init=False, repr=False)

    async def handle(self, state: SearchState, call_tool: CallTool) -> Reply | None:
        """Continue the open form with the human's response (``state.form_input``); None when the turn is not the form's.

        Only a response continues a form. A message without one means the pending stop went unanswered — the
        human rejected it, or went on to something else — so the form is over and the message is the
        model's. A stop that has not been shown yet (``unseen``) is shown instead.
        """
        session = state.form_fill
        if session is None:
            return None  # routing is the model's, via the handoff tool
        given = state.form_input
        if session.status == "opening" or not state.hitl or (given is None and not session.unseen):
            state.form_fill = None
            return None
        given = given or FormInput()
        return self._finish(state, session, await self._turn(session, given.values, given.decision, call_tool))

    async def open(self, state: SearchState, call_tool: CallTool) -> Reply | None:
        """Walk the form the model handed off (``start_workflow_form``); None if there is none.

        The subscription the model passed on fills the form's first page, and core's verdict on it is the
        stop like any other. So is core's refusal of the workflow itself (a key the handoff tool checked
        but core no longer knows): the form closes with it.
        """
        session = state.form_fill
        if session is None or session.status != "opening":
            return None
        logger.info(
            "Form-fill opened by the model",
            workflow=session.workflow_key,
            subscription_id=session.values.get(SUBSCRIPTION_ID),  # the model passes the one it knows with the handoff
        )
        session.status = "gathering"
        return self._finish(state, session, await self._walk(session, call_tool))

    # --- one turn ------------------------------------------------------------------------------------

    async def _turn(
        self, session: FormFillSession, values: Mapping[str, Any] | None, decision: Decision | None, call_tool: CallTool
    ) -> Reply:
        """What the response does: cancel; answer fields (the form is walked again); start, at the summary.

        Anything else — no answers, an approval that is not for the summary — is answered with the same stop.
        """
        if decision is Decision.CANCEL:
            session.status = "done"
            return self._reply(session, "cancelled")
        if values:
            session.values.update(values)
            return await self._walk(session, call_tool)
        if decision is Decision.START and session.status == "confirming":
            return await self._start(session, call_tool)
        return await self._walk(session, call_tool)

    @staticmethod
    def _finish(state: SearchState, session: FormFillSession, reply: Reply) -> Reply:
        state.form_fill = None if session.status == "done" else session
        return reply

    @staticmethod
    def _reply(session: FormFillSession, status: Any, **data: Any) -> Reply:
        return as_reply(FormReply(workflow_key=session.workflow_key, status=status, **data))

    # --- core's catalogue ---------------------------------------------------

    async def workflows(self, call_tool: CallTool) -> dict[str, str]:
        """Core's workflows, tasks included, as ``{key: description}``; cached briefly (static per deployment)."""
        now = time.monotonic()
        if self._catalogue is not None and now - self._catalogue_at < _WORKFLOWS_TTL:
            return self._catalogue
        listed = _WORKFLOW_LIST.validate_python(await call_tool(LIST_WORKFLOWS_TOOL, {}))
        self._catalogue = {wf.name: wf.description or wf.name for wf in listed}
        self._catalogue_at = now
        return self._catalogue

    # --- the walk ----------------------------------------------------------------------------------

    @staticmethod
    async def _page(session: FormFillSession, call_tool: CallTool, pages: list[dict[str, Any]]) -> WorkflowFormPage:
        """Core's verdict on ``pages``: the next page, the form complete, or the page it rejected with its errors."""
        request = GetWorkflowFormRequest(
            workflow_key=session.workflow_key, page_inputs=pages, include_schema=False, verdict="result"
        )
        return WorkflowFormPage.model_validate(await call_tool(GET_WORKFLOW_FORM_TOOL, request.model_dump()))

    async def _walk(self, session: FormFillSession, call_tool: CallTool) -> Reply:
        """Walk from page 0, submitting each page as it is known; stop where core does not accept one, or at the summary.

        Core is the only judge of a page: what is missing and what is wrong come back in its words, in one
        stop (gathering). A page of optional fields nobody has touched is asked once, since core would accept
        it as it is. The validated pages are committed to the session only when the walk stops, so a failure
        in the middle (an exception propagating to the adapter) leaves the session as it was.
        """
        pages: list[dict[str, Any]] = []
        interpreted: set[str] = set()
        session.pages = []  # this walk's pages only: a regenerated form leaves no stale field behind
        while len(pages) < _MAX_PAGES:
            try:
                page = await self._page(session, call_tool, pages)
            except ModelRetry as exc:  # no verdict on a page: core refuses the workflow itself, or is in trouble
                if not pages:  # nothing was submitted: core does not know the workflow, and the form closes
                    session.status = "done"
                    return self._reply(session, "failed", reason=str(exc))
                return self._page_stop(session, session.pages[-1], pages, reason=str(exc))  # asked again, with it
            if page.status == "rejected":  # values missing or wrong: the human's to fix, after one reading
                if await self._reinterpret(session, page.errors, interpreted):
                    pages, session.pages = [], []  # values changed: walk again from page 0
                    continue
                return self._page_stop(session, page, pages, page.errors)
            if page.complete:
                self._stop(session, pages, "confirming")
                return self._summary(session)
            session.pages.append(page)
            fields = [field for field in page.fields or [] if askable(field)]
            values = self._see_page(session, fields, pages)
            # A page of optional fields nobody has said anything about is asked once (a modify-note page is
            # only its optional note); whatever the caller replies, defaults then apply.
            untouched = not values and fields and not any(field.required for field in fields)
            if untouched and not any(field.name in session.asked for field in fields):
                return self._page_stop(session, page, [*pages, values])
            pages.append(values)
        session.status = "done"
        return self._reply(session, "failed", reason=f"the form did not complete after {_MAX_PAGES} pages")

    def _page_stop(
        self,
        session: FormFillSession,
        page: WorkflowFormPage,
        pages: list[dict[str, Any]],
        errors: Sequence[FormFieldError] = (),
        reason: str | None = None,
    ) -> Reply:
        """The stop at ``page``, the last of ``pages``: its fields as questions, with core's verdict on it.

        The pages before it are the validated ones; its fields count as asked. ``reason`` is a refusal that
        is no form verdict: the page is asked again with it, so a passing failure costs the human one
        answer, not the form. Only a stop with nothing to ask — a page without a field — closes the form.
        """
        fields = page.fields or []
        self._stop(session, pages[:-1], "gathering")
        session.asked.extend(field.name for field in fields if field.name not in session.asked)
        rejected = {str(error.loc[0]) for error in errors if error.loc}
        values = {**_given(session), **{name: value for name, value in pages[-1].items() if name not in rejected}}
        ask = questions(fields, values, errors, reason)
        if not ask:
            session.status = "done"
            return self._reply(session, "failed", reason=reason or "the form asks for nothing a person can answer")
        data = FormReply(
            workflow_key=session.workflow_key,
            status="gathering",
            page=page.page,
            title=page.title,
            rejected=list(errors),
            reason=reason,
            values=values,
            labels=self._labels(session, values),
        )
        return as_reply(data, ask=ask)

    async def _reinterpret(self, session: FormFillSession, errors: Sequence[FormFieldError], done: set[str]) -> bool:
        """Where core rejected a person's answers, ask the interpreter for the values — one call per page, once per answer.

        A picked option is its value, so this runs for what a person typed: a number in words, an option
        described, a structured field. True when any value changed (the walk starts over).
        """
        if self.interpret is None:
            return False
        form = form_model([page.fields or [] for page in session.pages])
        words: dict[str, str] = {}
        for error in errors:
            name = str(error.loc[0]) if error.loc else ""
            raw = session.values.get(name)
            if name not in form.model_fields or name in done or raw is None:
                continue
            done.add(name)
            answer = raw if isinstance(raw, str) else str(raw)
            if session.interpreted.get(name) != answer:  # the same words again: what was made of them stands
                session.interpreted[name] = answer
                words[name] = answer
        if not words:
            return False
        values = await self.interpret.answers(form, words)
        for name, value in values.items():
            session.values[name] = value
        return bool(values)

    @staticmethod
    def _stop(
        session: FormFillSession, pages: list[dict[str, Any]], status: Literal["gathering", "confirming"]
    ) -> None:
        session.page_inputs = pages
        session.status = status

    @staticmethod
    def _see_page(session: FormFillSession, fields: Sequence[FormField], pages: list[dict[str, Any]]) -> dict[str, Any]:
        """Collect what is known for the fields of the page after ``pages``: the caller's values, the obvious.

        A value goes to core exactly as sent; nothing here judges it. A required choice with exactly one
        option is taken without asking anyone (as the one-item list a single-select list wants), each walk
        anew: the options of a regenerated page may differ. Consent (``Accept``) counts for what it was
        given for — see ``_consented``.
        """
        values: dict[str, Any] = {}
        accepts: list[FormField] = []
        for field in fields:
            options = options_of(field) or []
            if field.format == ACCEPT:
                accepts.append(field)
            elif field.name in session.values:
                values[field.name] = session.values[field.name]
            elif field.required and single_pick(field) and len(options) == 1:
                (only,) = options
                values[field.name] = [only.value] if field.kind == "list" else only.value
        if accepts:
            seen = _fingerprint([*pages, values])
            for field in accepts:
                accepted = next((option.value for option in options_of(field) or []), None)
                if FormFillSkill._consented(session, field.name, accepted, page_index=len(pages), seen=seen):
                    values[field.name] = accepted
        return values

    @staticmethod
    def _consented(session: FormFillSession, name: str, accepted: Any, *, page_index: int, seen: str) -> bool:
        """Whether this page has the caller's consent for this field, given for what it shows now (``seen``).

        Consent is kept per page and field, with the fingerprint of the pages before it and the rest of its
        own: it holds through a re-walk that changes none of that, and is void once a correction does. A
        fresh consent is for the page being asked now and is consumed by it, never carried to a later page
        that asks the same thing.
        """
        key = f"{page_index}:{name}"
        if session.consents.get(key) == seen:
            return True
        if accepted is not None and session.values.get(name) == accepted:
            session.consents[key] = seen
            session.values.pop(name, None)
            return True
        return False

    @staticmethod
    def _create_args(session: FormFillSession) -> dict[str, Any]:
        """The ``create_workflow`` call: what the human approves is exactly what is sent."""
        return {WORKFLOW_KEY_PARAM: session.workflow_key, JSON_DATA_PARAM: session.page_inputs}

    @staticmethod
    def _labels(session: FormFillSession, values: Mapping[str, Any]) -> dict[str, Any]:
        """How the form shows each of ``values`` that is one of its field's options (an id says nothing to a person)."""
        fields = _fields(session)
        shown = {name: label_of(fields[name], value) for name, value in values.items() if name in fields}
        return {name: label for name, label in shown.items() if label is not None}

    def _summary(self, session: FormFillSession) -> Reply:
        """Every value to be submitted and the defaults that apply, with the create call for the human to approve.

        A form that ends in the workflow's own summary page (core's summary form) has its tables on the
        reply as well: what the workflow's author wants confirmed, as core made it of these very values.
        """
        given = _given(session)
        shown = self._labels(session, given)
        fields = _fields(session)
        defaults = {
            name: field.default
            for name, field in fields.items()
            if askable(field) and name not in given and not field.required
        }
        tables: list[Any] = [f.data for f in fields.values() if f.format == SUMMARY and isinstance(f.data, dict)]
        data = FormReply(
            workflow_key=session.workflow_key,
            status="confirming",
            values=given,
            labels=shown,
            defaults=defaults,
            summary=[table for table in tables if table.get("labels")],
        )
        # The call is shown as it will be made; ``labels`` only says what its ids stand for.
        args = {**self._create_args(session), **({"labels": shown} if shown else {})}
        hint = f"Start workflow `{session.workflow_key}` with these values?"
        return as_reply(data, approval=Approval(hint=hint, tool_name=CREATE_WORKFLOW_TOOL, args=args))

    async def _start(self, session: FormFillSession, call_tool: CallTool) -> Reply:
        """Start the workflow with exactly the validated pages. A start is never sent twice for one confirmation.

        The form reopens only on core's own verdict on the pages: a refusal is checked against the form
        tool, and a page it rejects is asked again, so nothing was started. After any other failure whether
        core started the process is unknown, and after an answer the form is done whatever the answer looks
        like — so in both cases it closes.
        """
        try:
            result = await call_tool(CREATE_WORKFLOW_TOOL, self._create_args(session))
        except Exception as exc:
            if isinstance(exc, ModelRetry):  # core refused: if that is its verdict on a page, the page is asked again
                verdict = await self._page(session, call_tool, session.page_inputs)
                if verdict.status == "rejected":
                    return self._page_stop(session, verdict, session.page_inputs[: verdict.page + 1], verdict.errors)
            logger.exception("Form-fill: create_workflow failed", workflow=session.workflow_key)
            session.status = "done"
            return self._reply(session, "failed", reason=str(exc) or type(exc).__name__)
        session.status = "done"
        try:
            process_id = str(ProcessIdSchema.model_validate(result).id)
        except ValidationError:  # core answered, so it started; what it answered goes back as it came
            logger.error("Form-fill: create_workflow answered without a process id", workflow=session.workflow_key)
            return self._reply(session, "started", reason=str(result))
        return self._reply(session, "started", process_id=process_id)


__all__ = ["CallTool", "FormFillSkill", "as_reply", "question", "questions", "single_pick", "unique_choices"]
