# Copyright 2019-2026 SURF, GÉANT.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The workflow form-fill skill: deterministic and LLM-free.

Over A2A the caller is another agent, so nothing here needs to *write* language: code walks the
multi-page form via core's MCP tools and every stop is a templated message in the contract the caller
reads back (see ``contract``). *Which* workflow a request asks for is the model's call: it hands off with
the ``start_workflow_form`` tool (``handoff``, which checks the key against core's catalogue) and ``open``
walks the first pages in the same turn. Everything after that is the literal contract — a JSON object keyed
by field name, ``yes`` / ``no`` / ``cancel`` — and core's own validation: values go to core as sent. One
skill turn is one caller message:

- opening (just handed off): the subscription the request names — or the one the model passed on — is
  checked against core's per-subscription listing; a workflow core cannot run on it closes with the
  reason and what the subscription can run instead. Otherwise the values the request states are taken
  and the form is **walked** from page 0.
- gathering: the values a JSON reply states are recorded, then the form is walked again from page 0; the
  walk stops at the first page with a required field nobody has supplied, or at the summary. Where core
  rejects a person's words (a kagent human), an ``Interpreter`` turns them into values once, then core
  decides again.
- confirming: corrections re-walk; ``yes`` starts (``create_workflow`` with exactly the last walk's
  validated pages) and ``no`` cancels.

Re-walking from page 0 every turn is what makes corrections free (pages after a changed answer are
regenerated by core) and keeps the session tiny; each page costs one MCP call. Routing by a typed decision
engine in front of the model, and prefilling pages from the conversation, live on the Jev branch.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from dataclasses import field as dc_field
from typing import Any, Protocol

import structlog
from orchestrator.core.schemas.mcp_tools import (
    GetWorkflowFormRequest,
    ListWorkflowsRequest,
    SubscriptionIdRequest,
    WorkflowFormPage,
)
from orchestrator.core.schemas.process import ProcessIdSchema
from orchestrator.core.schemas.workflow import SubscriptionWorkflowListsSchema, WorkflowSchema
from orchestrator.core.targets import Target
from pydantic import TypeAdapter
from pydantic_ai import ModelRetry

from orchestrator_agent.form_fill.contract import (
    ACCEPT_VALUE,
    NOT_OFFERED,
    SUBSCRIPTION_ID,
    FormCommand,
    ask_field,
    command,
    need_input,
    raw_pairs,
    render_blocked,
    render_cancelled,
    render_rejected,
    render_start_unknown,
    render_started,
    render_summary,
    uuids_in,
)
from orchestrator_agent.form_fill.core_bridge import error_detail, page_fields, rejected_fields
from orchestrator_agent.form_fill.interpret import Interpreter
from orchestrator_agent.state import Approval, AskField, FormField, FormFillSession, Reply, SearchState
from orchestrator_agent.tool_names import (
    CREATE_WORKFLOW_TOOL,
    GET_WORKFLOW_FORM_TOOL,
    JSON_DATA_PARAM,
    LIST_WORKFLOWS_TOOL,
    SUBSCRIPTION_WORKFLOWS_TOOL,
    WORKFLOW_KEY_PARAM,
)

logger = structlog.get_logger(__name__)

# Core's tool results are validated with core's own response models (the agent depends on orchestrator-core),
# and its tool arguments are built from core's request models — nothing here spells out a field of either.
_WORKFLOW_LIST: TypeAdapter[list[WorkflowSchema]] = TypeAdapter(list[WorkflowSchema])


class CallTool(Protocol):
    """Call one of core's MCP tools by name (bound to an open MCP session by the adapter)."""

    async def __call__(self, name: str, args: dict[str, Any]) -> Any: ...


_MAX_PAGES = 50  # a form that keeps producing pages is broken, not long
_WORKFLOWS_TTL = 300.0  # seconds the workflow catalogue is cached per skill instance


@dataclass
class FormFillSkill:
    interpret: Interpreter | None = None  # a person's answers core rejected -> the values the fields expect
    _catalogue: dict[str, str] | None = dc_field(default=None, init=False, repr=False)
    _creates: frozenset[str] = dc_field(default=frozenset(), init=False, repr=False)  # not about a subscription
    _catalogue_at: float = dc_field(default=0.0, init=False, repr=False)

    @staticmethod
    def wants(state: SearchState) -> bool:
        """Whether this message can be the skill's at all: a form is open."""
        return state.form_fill is not None

    async def handle(self, text: str, state: SearchState, call_tool: CallTool) -> Reply | None:
        """Handle one caller message; the reply, or None when this is not a form-fill message."""
        session = state.form_fill
        if session is None:
            return None  # routing is the model's, via the handoff tool
        if session.status == "opening":
            state.form_fill = None  # a handoff that was never walked (the turn failed): start over
            return None
        if session.status == "confirming":
            return self._finish(state, session, await self._confirm(text, session, call_tool))
        return self._finish(state, session, await self._gathering_turn(text, session, call_tool))

    async def open(self, state: SearchState, call_tool: CallTool) -> Reply | None:
        """Walk the form the model handed off (``start_workflow_form``); None if there is none or the key is unknown.

        The opening message is the caller's request: values it states (a JSON object, a bare subscription
        id) are taken, and the subscription it names — or the one the model passed on — is checked against
        core's available workflows: a workflow core cannot run on it closes with the reason.
        """
        session = state.form_fill
        if session is None or session.status != "opening":
            return None
        workflows = await self.workflows(call_tool)
        if session.workflow_key not in workflows:  # the handoff tool checks the key; a stale session may not
            logger.warning("Form-fill handoff to an unknown workflow", workflow=session.workflow_key)
            state.form_fill = None
            return None
        text = session.request
        ids = uuids_in(text)  # a bare id in the opening request names the subscription (never mid-form)
        subscription = session.values.get(SUBSCRIPTION_ID) or (ids[0] if len(ids) == 1 else None)
        logger.info("Form-fill opened by the model", workflow=session.workflow_key, subscription_id=subscription)
        session.status = "gathering"
        if subscription and session.workflow_key not in self._creates:  # a create is not about a subscription
            blocked = await self._blocked(str(subscription), session.workflow_key, call_tool)
            if blocked is not None:
                reason, runnable = blocked
                session.status = "done"
                reply = Reply(render_blocked(session.workflow_key, workflows[session.workflow_key], reason, runnable))
                return self._finish(state, session, reply)
        if subscription:
            session.values.setdefault(SUBSCRIPTION_ID, str(subscription))
        self._record_answers(text, session)
        return self._finish(state, session, await self._walk(session, call_tool))

    # --- one turn ------------------------------------------------------------------------------------

    async def _gathering_turn(self, text: str, session: FormFillSession, call_tool: CallTool) -> Reply:
        """Record what the message states and walk; ``cancel`` closes the form; anything else re-asks."""
        if self._record_answers(text, session):
            return await self._walk(session, call_tool)
        if command(text) is FormCommand.CANCEL:
            session.status = "done"
            return Reply(render_cancelled(session.workflow_key))
        return await self._walk(session, call_tool)  # literal contract: the same stop again

    @staticmethod
    def _finish(state: SearchState, session: FormFillSession, reply: Reply) -> Reply:
        state.form_fill = None if session.status == "done" else session
        return reply

    @staticmethod
    def _record_answers(text: str, session: FormFillSession) -> bool:
        """Record the values a JSON reply states; True when it stated any (the message is about the form).

        Values for fields not seen yet wait and apply when their page appears.
        """
        pairs = raw_pairs(text)
        session.values.update(pairs)
        return bool(pairs)

    # --- core's catalogue and per-subscription offer ---------------------------------------------------

    async def workflows(self, call_tool: CallTool) -> dict[str, str]:
        """User-facing workflows as ``{key: description}``, cached briefly (the catalogue is static per deployment)."""
        now = time.monotonic()
        if self._catalogue is not None and now - self._catalogue_at < _WORKFLOWS_TTL:
            return self._catalogue
        listed = _WORKFLOW_LIST.validate_python(
            await call_tool(LIST_WORKFLOWS_TOOL, ListWorkflowsRequest(is_task=False).model_dump(exclude_none=True))
        )
        self._catalogue = {wf.name: wf.description or wf.name for wf in listed}
        self._creates = frozenset(wf.name for wf in listed if wf.target == Target.CREATE)
        self._catalogue_at = now
        return self._catalogue

    async def _blocked(
        self, subscription_id: str, workflow_key: str, call_tool: CallTool
    ) -> tuple[str, dict[str, str]] | None:
        """Why core cannot run the workflow on the subscription now, with what it can run instead; None when it can.

        Unknown to core's per-subscription listing counts as not offered. A refused lookup (an unknown id,
        most likely) is not a verdict: the walk goes on and core's form judges the id.
        """
        try:
            listed = SubscriptionWorkflowListsSchema.model_validate(
                await call_tool(
                    SUBSCRIPTION_WORKFLOWS_TOOL, SubscriptionIdRequest(subscription_id=subscription_id).model_dump()
                )
            )
        except ModelRetry as exc:
            logger.warning(
                "Form-fill: subscription lookup refused", subscription_id=subscription_id, error=str(exc)[:200]
            )
            return None
        entries = [
            *listed.create,
            *listed.modify,
            *listed.terminate,
            *listed.system,
            *listed.reconcile,
            *listed.validate_,
        ]
        if not entries:
            return None  # nothing known about this subscription: no verdict
        offered = {wf.name: wf.reason for wf in entries}
        reason = offered.get(workflow_key, NOT_OFFERED)
        if reason is None:
            return None  # runnable
        catalogue = self._catalogue or {}
        runnable = {
            name: catalogue[name]
            for name, why in offered.items()
            if why is None and name in catalogue and name not in self._creates
        }
        logger.info(
            "Form-fill: blocked on subscription", subscription_id=subscription_id, workflow=workflow_key, reason=reason
        )
        return str(reason), runnable

    # --- the walk ----------------------------------------------------------------------------------

    async def _walk(self, session: FormFillSession, call_tool: CallTool) -> Reply:
        """Walk from page 0 with what is known; stop where values are needed (gathering) or at the summary (confirming).

        The pages are committed to the session only when the walk stops, so a failure in the middle (an
        exception propagating to the adapter) leaves the session as it was.
        """
        pages: list[dict[str, Any]] = []
        interpreted: set[str] = set()
        session.fields = {}  # this walk's pages only: a regenerated form leaves no stale field behind
        while len(pages) < _MAX_PAGES:
            try:
                page = WorkflowFormPage.model_validate(
                    await call_tool(
                        GET_WORKFLOW_FORM_TOOL,
                        GetWorkflowFormRequest(workflow_key=session.workflow_key, page_inputs=pages).model_dump(),
                    )
                )
            except ModelRetry as exc:  # core rejected the values
                if await self._reinterpret(session, str(exc), interpreted):
                    pages, session.fields = [], {}  # values changed: walk again from page 0
                    continue
                self._stop(session, pages, "gathering")
                return self._rejected(session, str(exc))  # the caller's to fix
            if page.complete:
                self._stop(session, pages, "confirming")
                return self._summary(session)

            schema = page.schema_ or {}
            fields = page_fields(schema)
            values = self._see_page(session, fields, page_index=len(pages))

            fillable = [f for f in fields if not f.display_only]
            missing = [f for f in fillable if f.required and f.name not in values]
            # A page nobody has said anything about — no required fields and nothing supplied — is asked once
            # (a modify-note page is only its optional note); whatever the caller replies, defaults then apply.
            untouched = not values and fillable and not any(f.name in session.asked for f in fillable)
            if missing or untouched:
                self._stop(session, pages, "gathering")
                session.asked.extend(f.name for f in fillable if f.name not in session.asked)
                return need_input(
                    session, page=page.page, title=schema.get("title"), fields=fields, values=values, missing=missing
                )
            pages.append(values)
        self._stop(session, pages, "gathering")
        return self._rejected(session, f"the form did not complete after {_MAX_PAGES} pages")

    async def _reinterpret(self, session: FormFillSession, error: str, done: set[str]) -> bool:
        """Where core rejected a person's answers, ask the interpreter for the values — one call per page, once per answer.

        A caller that is an agent sends the format the stop asked for, so this mostly never runs; through
        kagent the answers are a person's words. True when any value changed (the walk starts over).
        """
        if self.interpret is None:
            return False
        words: dict[str, str] = {}
        for name in rejected_fields(error):
            raw = session.values.get(name)
            if name not in session.fields or name in done or raw is None:
                continue
            done.add(name)
            answer = raw if isinstance(raw, str) else str(raw)
            if session.interpreted.get(name) != answer:  # the same words again: what was made of them stands
                session.interpreted[name] = answer
                words[name] = answer
        if not words:
            return False
        values = await self.interpret([session.fields[name] for name in words], words)
        for name, value in values.items():
            session.values[name] = value
        return bool(values)

    @staticmethod
    def _stop(session: FormFillSession, pages: list[dict[str, Any]], status: str) -> None:
        session.page_inputs = pages
        session.status = status  # type: ignore[assignment]  # one of the session's own literals

    @staticmethod
    def _see_page(session: FormFillSession, fields: list[FormField], *, page_index: int) -> dict[str, Any]:
        """Remember the page's fields and collect what is known for them: the caller's values, the obvious.

        A value goes to core as sent (an empty string leaves the field to its default). Consent (``Accept``)
        counts once, for the page it was given for, and is never carried to another page; a choice with
        exactly one option is taken without asking anyone.
        """
        session.fields.update({f.name: f for f in fields})
        values: dict[str, Any] = {}
        for f in fields:
            if f.display_only:
                continue
            if f.kind == "accept":
                if FormFillSkill._consented(session, f.name, page_index):
                    values[f.name] = ACCEPT_VALUE
                continue
            given = session.values.get(f.name)
            if given is not None and not (isinstance(given, str) and not given.strip()):
                values[f.name] = given
            elif f.kind == "choice" and f.options and len(f.options) == 1:
                (only,) = f.options
                values[f.name] = session.values[f.name] = [only] if f.as_list else only
        return values

    @staticmethod
    def _consented(session: FormFillSession, name: str, page_index: int) -> bool:
        """Whether this page has the caller's ``ACCEPTED`` for this field.

        Consent given earlier for this page holds through a re-walk; a fresh ``ACCEPTED`` is for the page
        being asked now and is consumed by it, never carried to a later page that asks the same thing.
        """
        if session.accepted.get(name) == page_index:
            return True
        if str(session.values.get(name, "")).strip() == ACCEPT_VALUE:
            session.accepted[name] = page_index
            session.values.pop(name, None)
            return True
        return False

    @staticmethod
    def _rejected(session: FormFillSession, error: str) -> Reply:
        """Core's rejection as the reply: the text names the fields; as questions, the rejected fields are asked again."""
        ask = [
            ask_field(session.fields[name], required=session.fields[name].required, problem=problem)
            for name, problem in rejected_fields(error).items()
            if name in session.fields
        ]
        if not ask:  # core named nothing the form knows: one free question with the whole reason
            question = f"The orchestrator rejected the values: {error_detail(error)}. Enter the corrected values."
            ask = [AskField(name=None, question=question)]
        return Reply(render_rejected(session, error), ask=ask)

    @staticmethod
    def _create_args(session: FormFillSession) -> dict[str, Any]:
        """The ``create_workflow`` call: what the human approves is exactly what is sent."""
        return {WORKFLOW_KEY_PARAM: session.workflow_key, JSON_DATA_PARAM: session.page_inputs}

    def _summary(self, session: FormFillSession) -> Reply:
        text = render_summary(session)
        return Reply(
            text, approval=Approval(hint=text, tool_name=CREATE_WORKFLOW_TOOL, args=self._create_args(session))
        )

    async def _start(self, session: FormFillSession, call_tool: CallTool) -> Reply:
        try:
            result = await call_tool(CREATE_WORKFLOW_TOOL, self._create_args(session))
        except ModelRetry as exc:  # core refused: correct and confirm again
            return self._rejected(session, str(exc))
        except Exception:
            # Whether core started the process is unknown: never retry a start blindly.
            logger.exception("Form-fill: create_workflow failed", workflow=session.workflow_key)
            session.status = "done"
            return Reply(render_start_unknown(session.workflow_key))
        session.status = "done"
        return Reply(render_started(session.workflow_key, str(ProcessIdSchema.model_validate(result).id)))

    # --- confirmation ------------------------------------------------------------------------------

    async def _confirm(self, text: str, session: FormFillSession, call_tool: CallTool) -> Reply:
        if self._record_answers(text, session):
            return await self._walk(session, call_tool)
        answer = command(text)
        if answer is FormCommand.YES:
            return await self._start(session, call_tool)
        if answer in (FormCommand.NO, FormCommand.CANCEL):
            session.status = "done"
            return Reply(render_cancelled(session.workflow_key))
        return await self._walk(session, call_tool)  # the summary again: the contract wants `yes` or `no`


__all__ = ["CallTool", "FormFillSkill"]
