# Copyright 2019-2026 SURF, GÉANT.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The workflow form-fill skill: a deterministic walk over core's form, answered by a human in the loop.

A form is filled through a human-in-the-loop transport only (kagent's extension over A2A, or LibreChat's
ask-user tool over chat completions): every stop of the skill is a pause that shows the human the page's
questions with their options, or the start to approve, and only their structured response continues the form. No chat text is read for a value or a
decision, by this code or by a model. *Which* workflow a request asks for is the model's call: it hands
off with the ``start_workflow_form`` tool (``handoff``, which checks the key against core's catalogue)
and ``open`` walks the first pages in the same turn. Core's own validation is the only validation. One
skill turn is one response of the human:

- opening (just handed off): the form is **walked** from page 0 with the subscription the model passed
  on; a subscription core will not run the workflow on is rejected by core's own subscription page, like
  any other value.
- gathering: the answers are recorded, then the form is walked again from page 0, each page submitted
  to core as it is known; the walk stops at the first page core does not accept — its fields are the
  questions, with core's message on the ones it rejected — or at the summary. Where core rejects what a
  person typed for a field, an ``Interpreter`` turns the words into the field's value once, then core
  decides again.
- confirming: the start is the human's approval of the ``create_workflow`` call (exactly the last walk's
  validated pages); a rejection cancels. A start is sent once: only core's own verdict on the pages
  reopens the form, any other failure closes it.

A message that carries no response means the pending stop went unanswered: the form is over and the
message is the model's. The one exception is a stop that has not been shown yet (``unseen``): a parent
runtime pauses once per call, so the stop that answers a response only reaches the human when the
parent calls again, and that call shows it.

Re-walking from page 0 every turn is what makes corrections free (pages after a changed answer are
regenerated by core) and keeps the session tiny; each page costs one MCP call. Routing by a typed decision
engine in front of the model, and prefilling pages from the conversation, live on the Jev branch.
"""

from __future__ import annotations

import hashlib
import json
import time
from collections.abc import Collection, Mapping, Sequence
from dataclasses import dataclass, replace
from dataclasses import field as dc_field
from typing import Any, Literal, Protocol

import structlog
from orchestrator.core.schemas.mcp_tools import GetWorkflowFormRequest, ListWorkflowsRequest, WorkflowFormPage
from orchestrator.core.schemas.process import ProcessIdSchema
from orchestrator.core.schemas.workflow import WorkflowSchema
from pydantic import BaseModel, TypeAdapter, ValidationError
from pydantic.fields import FieldInfo
from pydantic_ai import ModelRetry

from orchestrator_agent.form_fill.core_bridge import (
    choices,
    form_errors,
    form_model,
    is_accept,
    is_list,
    is_single_pick,
    label_of,
    labels,
    page_model,
    summaries,
    value_type,
    widget_mark,
)
from orchestrator_agent.form_fill.interpret import Chooser, Interpreter
from orchestrator_agent.form_fill.widgets import MAX_INLINE, CascadeWidget, FieldWidget, GraphQL, WidgetContext
from orchestrator_agent.form_fill.widgets.enrich import EnrichedPage, LongList, enrich
from orchestrator_agent.form_fill.widgets.resolve import Resolution, resolve_answer, shown_as
from orchestrator_agent.state import (
    ACCEPT_VALUE,
    SUBSCRIPTION_ID,
    Approval,
    AskField,
    Decision,
    FormError,
    FormFillSession,
    FormInput,
    FormReply,
    Reply,
    SearchState,
)
from orchestrator_agent.tool_names import (
    CREATE_WORKFLOW_TOOL,
    GET_WORKFLOW_FORM_TOOL,
    JSON_DATA_PARAM,
    LIST_WORKFLOWS_TOOL,
    WORKFLOW_KEY_PARAM,
)

logger = structlog.get_logger(__name__)

# Core's tool results are validated with core's own response models (the agent depends on orchestrator-core),
# and its tool arguments are built from core's request models — nothing here spells out a field of either.
_WORKFLOW_LIST: TypeAdapter[list[WorkflowSchema]] = TypeAdapter(list[WorkflowSchema])


class CallTool(Protocol):
    """Call one of core's MCP tools by name (bound to an open MCP session by the adapter)."""

    async def __call__(self, name: str, args: dict[str, Any]) -> Any: ...


_MAX_PAGES = 50  # a form that keeps producing pages is broken, not long
_WORKFLOWS_TTL = 300.0  # seconds the workflow catalogue is cached per skill instance


_MISSING = "missing"  # pydantic's error type for a required field without a value: the question says so already

# What a stop says about a widget field (``AskField.hint``): the size of a long list, what typed words matched.
LONG_LIST_HINT = "Type a name or part of it — {total} options."
SEVERAL_FIT = "More than one option fits what was typed: pick one, or type more of the name."
TOO_MANY_FIT = "Many options fit what was typed: type more of the name."
NOTHING_FIT = "Nothing matched {words}: type another name."
NO_OPTIONS = "There are no options for {title} here."
CHANGE_STEP = "Choose another {step}"  # the answer that goes back to a cascade field's steps (another node)


async def _no_graphql(query: str, variables: Mapping[str, Any] | None = None) -> dict[str, Any]:
    raise RuntimeError("no GraphQL endpoint of core is configured for the form-fill widgets")


def as_reply(data: FormReply, *, ask: Sequence[AskField] | None = None, approval: Approval | None = None) -> Reply:
    return Reply(data.as_text(), ask=ask, approval=approval)


def _waits(info: FieldInfo) -> bool:
    """Whether a widget field waits for another value before it has options (``later``)."""
    return bool((widget_mark(info) or {}).get("later"))


def questions(
    model: type[BaseModel],
    values: Mapping[str, Any],
    errors: Sequence[FormError],
    reason: str | None = None,
    *,
    untouched: bool = True,
    asked: Collection[str] = (),
) -> list[AskField]:
    """The stop as questions for the human: the fields core rejected, with its message, then the unanswered ones.

    ``untouched`` is false when the verdict is on the whole form rather than a page: only what core rejected
    is asked. A page core refused without naming one of its fields — its errors name none, or the refusal
    is no form verdict at all (``reason``) — is asked again in full, the first question with what core said.
    A field waiting for another value (``later``) is left out while anything else is asked; when nothing else
    is, it is asked as typed text, like a field without its widget, so it never leaves a stop with no question.
    An optional field the person was ``asked`` and left at its default is not asked again. A field asked for a
    step that comes before its value (a node, before the port) ends the stop: what follows it on the page may
    depend on that choice, so it is asked with the value, on the next stop.
    """
    waiting = {name for name, info in model.model_fields.items() if _waits(info)}
    found = _questions(model, values, errors, reason, untouched, waiting, asked) or _questions(
        model, values, errors, reason, untouched, set(), asked
    )
    return _up_to_a_step(model, found)


def _up_to_a_step(model: type[BaseModel], found: list[AskField]) -> list[AskField]:
    """The questions up to the first one asked for a step (in page order); all of them when none is."""
    order = {name: index for index, name in enumerate(model.model_fields)}
    steps = [order[field.name] for field in found if (widget_mark(model.model_fields[field.name]) or {}).get("step")]
    return [field for field in found if order[field.name] <= min(steps)] if steps else found


def _questions(
    model: type[BaseModel],
    values: Mapping[str, Any],
    errors: Sequence[FormError],
    reason: str | None,
    untouched: bool,
    waiting: set[str],
    asked: Collection[str],
) -> list[AskField]:
    """``questions``, leaving out the ``waiting`` fields and core's errors on them."""
    fields = {name: info for name, info in model.model_fields.items() if name not in waiting}
    errors = [error for error in errors if not (error["loc"] and str(error["loc"][0]) in waiting)]
    problems: dict[str, str] = {}
    for error in errors:
        if error["loc"] and (name := str(error["loc"][0])) in fields:
            problems.setdefault(name, "" if error["type"] == _MISSING else str(error["msg"]))
    if (errors or reason) and not problems and untouched:
        said = "; ".join(str(error["msg"]) for error in errors) or str(reason)
        problems = {name: said if index == 0 else "" for index, name in enumerate(fields)}
    found = [question(name, fields[name], problem) for name, problem in problems.items()]
    if untouched:
        open_ = {name: info for name, info in fields.items() if name not in problems and name not in values}
        found += [question(name, info) for name, info in open_.items() if info.is_required() or name not in asked]
    return found


def question(name: str, info: FieldInfo, problem: str = "") -> AskField:
    """One field as a question: its title, whether it is required, its options as chips, core's message if it rejected the answer.

    Nothing spells out what the field expects: a person answers in words, the interpreter has the schema.
    """
    note = "required" if info.is_required() else "optional — leave empty to keep the default"
    text = f"{info.title or name} (`{name}`, {note})" + (f" — {problem}" if problem else "")
    options: tuple[Any, ...] = ()
    if is_accept(info):
        options = (ACCEPT_VALUE,)
    elif (allowed := choices(info)) is not None:
        options = allowed
    elif value_type(info) is bool:
        options = (True, False)
    shown = labels(info)
    mark = widget_mark(info) or {}
    hint = LONG_LIST_HINT.format(total=mark["total"]) if mark.get("total") else ""
    if "total" in mark and not mark["total"]:  # a widget field whose source has nothing to offer
        hint = NO_OPTIONS.format(title=info.title or name)
    if stepped := mark.get("stepped"):  # its options follow from steps chosen first: offer to choose again
        change = CHANGE_STEP.format(step=" / ".join(stepped))
        options, hint = (*options, change), " ".join(filter(None, (hint, f'Pick "{change}" to go back.')))
    return AskField(
        name=name,
        question=text,
        choices=tuple(shown.get(str(value), str(value)) for value in options),  # the human sees labels
        values=options,
        multiple=is_list(info),
        required=info.is_required(),
        title=info.title or name,
        problem=problem,
        hint=hint,
    )


def offered(reply: Reply, unresolved: Mapping[str, Resolution]) -> Reply:
    """The stop, with what resolving said about each field whose words it could not resolve."""
    if not reply.ask or not unresolved:
        return reply
    return replace(reply, ask=[_offer(field, unresolved.get(field.name)) for field in reply.ask])


def _offer(field: AskField, outcome: Resolution | None) -> AskField:
    """A field asked again: the options that fit as chips, or why nothing is offered."""
    match outcome:
        case None:
            return field
        case Resolution(candidates=candidates) if 0 < len(candidates) <= MAX_INLINE:
            labels, values = tuple(o.label for o in candidates), tuple(o.value for o in candidates)
            return replace(field, choices=labels, values=values, hint=SEVERAL_FIT)
        case Resolution(candidates=candidates) if candidates:
            return replace(field, hint=TOO_MANY_FIT)
        case _:
            return replace(field, hint=NOTHING_FIT.format(words=", ".join(f"'{w}'" for w in outcome.unmatched)))


def _record(session: FormFillSession, name: str, choice: LongList, outcome: Resolution) -> None:
    """Keep what the words resolved to in place of the words; drop words that did not resolve (core never sees them).

    The answer to a cascade field's step is that step's choice, kept with the field's steps: the field has no
    value yet, and the next walk asks its next step or its value.
    """
    if choice.step is not None:
        session.values.pop(name, None)
        if outcome.resolved:
            session.steps.setdefault(name, {})[choice.step] = outcome.value
        return
    if outcome.resolved:
        session.values[name] = outcome.value
        session.resolved[name] = {"value": outcome.value, "label": shown_as(choice, outcome.value)}
    else:
        session.values.pop(name, None)
        session.resolved.pop(name, None)


def _goes_back(choice: LongList, answer: Any) -> bool:
    """Whether the answer to a field asked after its steps is the choice to go back to them (another node)."""
    stepped = isinstance(answer, str) and choice.step is None and isinstance(choice.widget, CascadeWidget)
    return stepped and answer.strip().casefold().startswith(CHANGE_STEP.format(step="").strip().casefold())


def _takes_only_option(info: FieldInfo) -> bool:
    """Whether a field's only option is taken without asking: a required choice the form itself offers, not a widget's."""
    return info.is_required() and is_single_pick(info) and widget_mark(info) is None


def _stepped(widget_choices: Mapping[str, LongList], session: FormFillSession) -> bool:
    """Whether a cascade field asked for a step now has that step chosen (so the page asks what comes next)."""
    return any(
        choice.step is not None and choice.step in session.steps.get(name, {})
        for name, choice in widget_choices.items()
    )


def _waiting(schemas: Sequence[Mapping[str, Any]]) -> list[str]:
    """The widget fields of these pages that wait for another value before they have options."""
    return list(
        dict.fromkeys(
            name for schema in schemas for name, info in page_model(schema).model_fields.items() if _waits(info)
        )
    )


def _given(session: FormFillSession) -> dict[str, Any]:
    """The validated pages' values as one mapping: what would be submitted (a later page wins a name)."""
    return {name: value for page in session.page_inputs for name, value in page.items()}


def _fingerprint(pages: list[dict[str, Any]]) -> str:
    """What a consent is given for — the pages before it and the rest of its own — as one comparable string."""
    return hashlib.sha256(json.dumps(pages, sort_keys=True, default=str).encode()).hexdigest()


@dataclass
class FormFillSkill:
    interpret: Interpreter | None = None  # a person's answers core rejected -> the values the fields expect
    widgets: Sequence[FieldWidget] = ()  # the formats whose options core leaves to the frontend (``form_fill.widgets``)
    graphql: GraphQL | None = None  # core's GraphQL API, for the widgets that read it
    choose: Chooser | None = None  # words a person typed for a widget field -> the options they fit
    _catalogue: dict[str, str] | None = dc_field(default=None, init=False, repr=False)
    _catalogue_at: float = dc_field(default=0.0, init=False, repr=False)

    async def handle(self, state: SearchState, call_tool: CallTool) -> Reply | None:
        """Continue the open form with the human's response (``state.form_input``); None when the turn is not the form's.

        Only a response continues a form. A message without one means the pending stop went unanswered — the
        human rejected it, or went on to something else — so the form is over and the message is the
        model's. A stop that has not been shown yet (``unseen``) is shown instead.
        """
        session = state.form_fill
        if session is None:
            return None  # routing is the model's, via the handoff tool
        given = state.form_input
        if session.status == "opening" or not state.hitl or (given is None and not session.unseen):
            state.form_fill = None
            return None
        given = given or FormInput()
        return self._finish(state, session, await self._turn(session, given.values, given.decision, call_tool))

    async def open(self, state: SearchState, call_tool: CallTool) -> Reply | None:
        """Walk the form the model handed off (``start_workflow_form``); None if there is none.

        The subscription the model passed on fills the form's first page, and core's verdict on it is the
        stop like any other. So is core's refusal of the workflow itself (a key the handoff tool checked
        but core no longer knows): the form closes with it.
        """
        session = state.form_fill
        if session is None or session.status != "opening":
            return None
        logger.info(
            "Form-fill opened by the model",
            workflow=session.workflow_key,
            subscription_id=session.values.get(SUBSCRIPTION_ID),  # the model passes the one it knows with the handoff
        )
        session.status = "gathering"
        return self._finish(state, session, await self._walk(session, call_tool))

    # --- one turn ------------------------------------------------------------------------------------

    async def _turn(
        self, session: FormFillSession, values: Mapping[str, Any] | None, decision: Decision | None, call_tool: CallTool
    ) -> Reply:
        """What the response does: cancel; answer fields (the form is walked again); start, at the summary.

        Anything else — no answers, an approval that is not for the summary — is answered with the same stop.
        """
        if decision is Decision.CANCEL:
            session.status = "done"
            return self._reply(session, "cancelled")
        if values:
            session.values.update(values)
            return await self._walk(session, call_tool)
        if decision is Decision.START and session.status == "confirming":
            return await self._start(session, call_tool)
        return await self._walk(session, call_tool)

    @staticmethod
    def _finish(state: SearchState, session: FormFillSession, reply: Reply) -> Reply:
        state.form_fill = None if session.status == "done" else session
        return reply

    @staticmethod
    def _reply(session: FormFillSession, status: Any, **data: Any) -> Reply:
        return as_reply(FormReply(workflow_key=session.workflow_key, status=status, **data))

    # --- core's catalogue ---------------------------------------------------

    async def workflows(self, call_tool: CallTool) -> dict[str, str]:
        """Core's workflows, tasks included, as ``{key: description}``; cached briefly (static per deployment)."""
        now = time.monotonic()
        if self._catalogue is not None and now - self._catalogue_at < _WORKFLOWS_TTL:
            return self._catalogue
        # Core's tool does not take a call without a filter, so the catalogue is asked for in its two halves.
        listed = [
            workflow
            for is_task in (False, True)
            for workflow in _WORKFLOW_LIST.validate_python(
                await call_tool(
                    LIST_WORKFLOWS_TOOL, ListWorkflowsRequest(is_task=is_task).model_dump(exclude_none=True)
                )
            )
        ]
        self._catalogue = {wf.name: wf.description or wf.name for wf in listed}
        self._catalogue_at = now
        return self._catalogue

    # --- the walk ----------------------------------------------------------------------------------

    async def _walk(self, session: FormFillSession, call_tool: CallTool) -> Reply:
        """Walk from page 0, submitting each page as it is known; stop where core does not accept one, or at the summary.

        Core is the only judge of a page: what is missing and what is wrong come back in its words, in one
        stop (gathering). A page of optional fields nobody has touched is asked once, since core would accept
        it as it is. The validated pages are committed to the session only when the walk stops, so a failure
        in the middle (an exception propagating to the adapter) leaves the session as it was.
        """
        pages: list[dict[str, Any]] = []
        interpreted: set[str] = set()
        session.pages = []  # this walk's pages only: a regenerated form leaves no stale field behind
        while len(pages) < _MAX_PAGES:
            try:
                page = WorkflowFormPage.model_validate(
                    await call_tool(
                        GET_WORKFLOW_FORM_TOOL,
                        GetWorkflowFormRequest(workflow_key=session.workflow_key, page_inputs=pages).model_dump(),
                    )
                )
            except ModelRetry as exc:  # core did not accept the last page: values missing or wrong
                if not pages:  # no page was submitted: core refuses the workflow itself, and the form closes
                    session.status = "done"
                    return self._reply(session, "failed", reason=str(exc))
                if await self._reinterpret(session, str(exc), interpreted):
                    pages, session.pages = [], []  # values changed: walk again from page 0
                    continue
                return self._page_stop(session, pages, str(exc))  # the human's to fix
            if page.complete:
                self._stop(session, pages, "confirming")
                return self._summary(session)

            enriched, unresolved = await self._enriched(session, call_tool, pages, page.schema_ or {})
            session.pages.append(enriched.schema)
            model = page_model(enriched.schema)
            values = self._see_page(session, model, pages)
            if unresolved:  # words that are no option: the page is asked again (with them), never submitted with them
                asked = {name: value for name, value in values.items() if name not in unresolved}
                return offered(self._page_stop(session, [*pages, asked]), unresolved)
            fields = model.model_fields
            # A page of optional fields nobody has said anything about is asked once (a modify-note page is
            # only its optional note); whatever the caller replies, defaults then apply. So is a field that
            # waited for another value at the last stop and has its options now.
            untouched = not values and fields and not any(f.is_required() for f in fields.values())
            offers = any(name in session.waiting and name not in values for name in enriched.choices)
            if offers or (untouched and not any(name in session.asked for name in fields)):
                return self._page_stop(session, [*pages, values])
            pages.append(values)
        session.status = "done"
        return self._reply(session, "failed", reason=f"the form did not complete after {_MAX_PAGES} pages")

    async def _enriched(
        self, session: FormFillSession, call_tool: CallTool, pages: list[dict[str, Any]], schema: dict[str, Any]
    ) -> tuple[EnrichedPage, dict[str, Resolution]]:
        """The page with its widgets' options, its answered widget fields resolved; those that were not, by name.

        A widget reads the values known so far, so once resolving changed what it read — a typed name became
        its option, a cascade step was chosen — the page is enriched and resolved once more (and only once).
        """
        ctx = self._widget_context(session, call_tool, pages)
        enriched = await enrich(schema, self.widgets, ctx, session.steps)
        unresolved = await self._resolve(session, enriched.choices, ctx)
        resolved = self._widget_context(session, call_tool, pages)
        if resolved.values == ctx.values and not _stepped(enriched.choices, session):
            return enriched, unresolved
        enriched = await enrich(schema, self.widgets, resolved, session.steps)
        return enriched, {**unresolved, **await self._resolve(session, enriched.choices, resolved)}

    def _widget_context(
        self, session: FormFillSession, call_tool: CallTool, pages: list[dict[str, Any]]
    ) -> WidgetContext:
        """What a widget may use on this page: core's APIs, and every value known so far."""
        known = {name: value for page in pages for name, value in page.items()}
        return WidgetContext(
            call_tool=call_tool, graphql=self.graphql or _no_graphql, values={**known, **session.values}
        )

    async def _resolve(
        self, session: FormFillSession, widget_choices: Mapping[str, LongList], ctx: WidgetContext
    ) -> dict[str, Resolution]:
        """Each answered widget field of the page resolved to its options in place; those that were not, by name.

        Every widget field with options is resolved, chips included: core takes any string for some of them
        (``CustomerId``), and a transport takes typed text next to the chips. A picked chip is one of the
        options and stands without a model call. A resolved value replaces the words, so the next walk finds
        it among the options and reads nothing again.
        """
        back = {name for name, choice in widget_choices.items() if _goes_back(choice, session.values.get(name))}
        for name in back:  # "Choose another node": the field's steps are asked again, from the first
            session.steps.pop(name, None)
            session.values.pop(name, None)
            session.resolved.pop(name, None)
        answered = {
            name: choice for name, choice in widget_choices.items() if session.values.get(name) not in (None, "", [])
        }
        outcomes = {
            name: await resolve_answer(choice, session.values[name], ctx, self.choose)
            for name, choice in answered.items()
        }
        for name, outcome in outcomes.items():
            _record(session, name, widget_choices[name], outcome)
        return {name: outcome for name, outcome in outcomes.items() if not outcome.resolved}

    def _page_stop(self, session: FormFillSession, pages: list[dict[str, Any]], error: str | None = None) -> Reply:
        """The stop at the last of ``pages``: its fields as questions, with core's verdict on it (none when it was never submitted).

        The pages before it are the validated ones; the fields it asks count as asked.
        """
        schema = session.pages[-1]
        model = page_model(schema)
        self._stop(session, pages[:-1], "gathering")
        reply = self._gathering(session, model, pages[-1], error, page=len(pages) - 1, title=schema.get("title"))
        session.asked.extend(field.name for field in reply.ask or () if field.name not in session.asked)
        return reply

    def _gathering(
        self,
        session: FormFillSession,
        model: type[BaseModel],
        submitted: Mapping[str, Any],
        error: str | None,
        *,
        page: int | None = None,
        title: str | None = None,
    ) -> Reply:
        """Core's verdict on ``submitted`` as the stop: the questions to answer, its errors as they are, the values so far.

        ``page`` is None when the verdict is on the whole form (core refused the start): only what it
        rejected is asked again. A refusal that is no form verdict (a ``reason``) leaves the form open: the
        page is asked again with it, so a passing failure costs the human one answer, not the form. Only a
        stop with nothing to ask — a page without a field — closes the form.
        """
        errors = form_errors(error) if error else []
        reason = error if error and not errors else None  # a refusal that is not a form body, as it came
        rejected = {str(e["loc"][0]) for e in errors if e["loc"]}
        values = {**_given(session), **{name: value for name, value in submitted.items() if name not in rejected}}
        ask = questions(model, values, errors, reason, untouched=page is not None, asked=session.asked)
        if not ask:
            session.status = "done"
            return self._reply(session, "failed", reason=error or "the form asks for nothing a person can answer")
        data = FormReply(
            workflow_key=session.workflow_key,
            status="gathering",
            page=page,
            title=title,
            rejected=errors,
            reason=reason,
            values=values,
            labels=self._labels(session, values),
        )
        return as_reply(data, ask=ask)

    async def _reinterpret(self, session: FormFillSession, error: str, done: set[str]) -> bool:
        """Where core rejected a person's answers, ask the interpreter for the values — one call per page, once per answer.

        A picked option is its value, so this runs for what a person typed: a number in words, an option
        described, a structured field. True when any value changed (the walk starts over).
        """
        if self.interpret is None:
            return False
        form = form_model(session.pages)
        words: dict[str, str] = {}
        for problem in form_errors(error):
            name = str(problem["loc"][0]) if problem["loc"] else ""
            raw = session.values.get(name)
            if name not in form.model_fields or widget_mark(form.model_fields[name]) or name in done or raw is None:
                continue
            done.add(name)
            answer = raw if isinstance(raw, str) else str(raw)
            if session.interpreted.get(name) != answer:  # the same words again: what was made of them stands
                session.interpreted[name] = answer
                words[name] = answer
        if not words:
            return False
        values = await self.interpret.answers(form, words)
        for name, value in values.items():
            session.values[name] = value
        return bool(values)

    @staticmethod
    def _stop(
        session: FormFillSession, pages: list[dict[str, Any]], status: Literal["gathering", "confirming"]
    ) -> None:
        session.page_inputs = pages
        session.status = status
        session.waiting = _waiting(session.pages)

    @staticmethod
    def _see_page(session: FormFillSession, model: type[BaseModel], pages: list[dict[str, Any]]) -> dict[str, Any]:
        """Collect what is known for the fields of the page after ``pages``: the caller's values, the obvious.

        A value goes to core exactly as sent; nothing here judges it. A required choice of the form's own with
        exactly one option is taken without asking anyone (as the one-item list a single-select list wants),
        each walk anew: the options of a regenerated page may differ. A widget field's only option is never
        taken: its options are what the network has now (one free port), and choosing it is the person's. A widget field still waiting for its options
        sends nothing: no value of it is one of its options yet. Consent (``Accept``) counts for what it was
        given for — see ``_consented``.
        """
        values: dict[str, Any] = {}
        accepts: list[str] = []
        for name, info in model.model_fields.items():
            if is_accept(info):
                accepts.append(name)
            elif name in session.values and not _waits(info):
                values[name] = session.values[name]
            elif _takes_only_option(info) and len(options := choices(info) or ()) == 1:
                (only,) = options
                values[name] = [only] if is_list(info) else only
        if accepts:
            seen = _fingerprint([*pages, values])
            for name in accepts:
                if FormFillSkill._consented(session, name, page_index=len(pages), seen=seen):
                    values[name] = ACCEPT_VALUE
        return values

    @staticmethod
    def _consented(session: FormFillSession, name: str, *, page_index: int, seen: str) -> bool:
        """Whether this page has the caller's ``ACCEPTED`` for this field, given for what it shows now (``seen``).

        Consent is kept per page and field, with the fingerprint of the pages before it and the rest of its
        own: it holds through a re-walk that changes none of that, and is void once a correction does. A
        fresh ``ACCEPTED`` is for the page being asked now and is consumed by it, never carried to a later
        page that asks the same thing.
        """
        key = f"{page_index}:{name}"
        if session.consents.get(key) == seen:
            return True
        if session.values.get(name) == ACCEPT_VALUE:
            session.consents[key] = seen
            session.values.pop(name, None)
            return True
        return False

    @staticmethod
    def _create_args(session: FormFillSession) -> dict[str, Any]:
        """The ``create_workflow`` call: what the human approves is exactly what is sent."""
        return {WORKFLOW_KEY_PARAM: session.workflow_key, JSON_DATA_PARAM: session.page_inputs}

    @staticmethod
    def _labels(session: FormFillSession, values: Mapping[str, Any]) -> dict[str, Any]:
        """How the form shows each of ``values`` that is one of its field's options (an id says nothing to a person)."""
        fields = form_model(session.pages).model_fields
        shown = {name: label_of(fields[name], value) for name, value in values.items() if name in fields}
        resolved = {
            name: kept["label"]
            for name, kept in session.resolved.items()
            if name in values and values[name] == kept["value"]
        }
        return {**resolved, **{name: label for name, label in shown.items() if label is not None}}

    def _summary(self, session: FormFillSession) -> Reply:
        """Every value to be submitted and the defaults that apply, with the create call for the human to approve.

        A form that ends in the workflow's own summary page (core's summary form) has its tables on the
        reply as well: what the workflow's author wants confirmed, as core made it of these very values.
        """
        given = _given(session)
        shown = self._labels(session, given)
        defaults = {
            name: info.default
            for name, info in form_model(session.pages).model_fields.items()
            if name not in given and not info.is_required()
        }
        data = FormReply(
            workflow_key=session.workflow_key,
            status="confirming",
            values=given,
            labels=shown,
            defaults=defaults,
            summary=[table for schema in session.pages for table in summaries(schema)],
        )
        # The call is shown as it will be made; ``labels`` only says what its ids stand for.
        args = {**self._create_args(session), **({"labels": shown} if shown else {})}
        hint = f"Start workflow `{session.workflow_key}` with these values?"
        return as_reply(data, approval=Approval(hint=hint, tool_name=CREATE_WORKFLOW_TOOL, args=args))

    async def _start(self, session: FormFillSession, call_tool: CallTool) -> Reply:
        """Start the workflow with exactly the validated pages. A start is never sent twice for one confirmation.

        The form reopens only on core's own verdict on the pages (its validation errors): nothing was started.
        After any other failure whether core started the process is unknown, and after an answer the form
        is done whatever the answer looks like — so in both cases it closes.
        """
        try:
            result = await call_tool(CREATE_WORKFLOW_TOOL, self._create_args(session))
        except Exception as exc:
            error = str(exc)
            if isinstance(exc, ModelRetry) and form_errors(error):  # core refused the pages: correct and confirm again
                session.status = "gathering"
                return self._gathering(session, form_model(session.pages), _given(session), error)
            logger.exception("Form-fill: create_workflow failed", workflow=session.workflow_key)
            session.status = "done"
            return self._reply(session, "failed", reason=error or type(exc).__name__)
        session.status = "done"
        try:
            process_id = str(ProcessIdSchema.model_validate(result).id)
        except ValidationError:  # core answered, so it started; what it answered goes back as it came
            logger.error("Form-fill: create_workflow answered without a process id", workflow=session.workflow_key)
            return self._reply(session, "started", reason=str(result))
        return self._reply(session, "started", process_id=process_id)


__all__ = [
    "CHANGE_STEP",
    "NO_OPTIONS",
    "LONG_LIST_HINT",
    "NOTHING_FIT",
    "SEVERAL_FIT",
    "TOO_MANY_FIT",
    "CallTool",
    "FormFillSkill",
    "as_reply",
    "offered",
    "question",
    "questions",
]
