name: Linting

on:
  push:
    branches: [main]
  pull_request:

env:
  UV_LOCKED: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.8"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev

      - name: Check with mypy
        run: uv run mypy .

      - name: Cache pre-commit hooks
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files
        env:
          SKIP: mypy
