name: Tests

on:
  push:
    branches: [main]
  pull_request:

env:
  UV_LOCKED: true

jobs:
  test:
    name: Tests Python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.8"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest --cov-branch --cov=orchestrator_agent --cov-report=xml
